:stem: latexmath
:xrefstyle: short
= Presentation of the team

Created in January 2021 within ICube laboratory at the University of Strasbourg, MLMS\footnote{MLMS : \url{https://mlms.icube.unistra.fr/en/index.php/Presentation}} ("Machine Learning, Modélisation et Simulation") team is interested in data, models and simulations for medical science and human motion. It brings together computer scientists, mathematicians, bio-mechanicians, and neuroscientists to develop functional, physical, and geometric models around a transverse axis "Assistance to medical interventions by computer". MLMS hosts the Inria MIMESIS\footnote{MIMESIS : \url{https://mimesis.inria.fr/}} project-team as a sub-team. The MIMESIS research team aims at creating real-time digital twins of an organ, with main application domains as surgical training and surgical guidance during complex interventions. In 2023, a new inria project-team NECTARINE will be created within MLMS, who will focus on scientific challenges related to neuro-stimulation in the clinical context. 

MIMESIS, directed by Stéphane Cotin, is a joint Inria\footnote{Inria : \url{https://www.inria.fr/fr}} ("Institut national de recherche en sciences et technologies du numérique") and CNRS\footnote{CNRS : \url{https://www.cnrs.fr/fr}} ("Centre national de la recherche scientifique") Research Team. The Mimesis research team is working on a set of scientific challenges in scientific computing, data assimilation, machine learning and control, with the goal of creating real-time digital twins of an organ.

