:stem: latexmath
:xrefstyle: short
= Scientific Context

Finite element methods (FEM) are used to numerically approximate the solution of partial differential equations. These equations can, for example, represent analytically the dynamic behavior of certain physical systems (mechanical, thermodynamic, acoustic, etc.). Among other things, it is a discrete algorithm for determining the approximate solution of a partial differential equation (PDE) on a compact domain with boundary conditions. 

The standard FEM method, which requires precise meshing of the domain under consideration and, in particular, fitting with its boundary, has its limitations. In particular, in the medical field, meshing complex and evolving geometries such as organs (e.g. the liver) can be very costly. More specifically, in the application context of creating real-time digital twins of an organ, the standard FEM method would require complete remeshing of the organ each time it is deformed, which in practice is not workable. 

This is why other methods, known as non-conformal finite element methods, have emerged in the last few years. These include CutFEM \cite{burman_cutfem_2015} or XFEM \cite{moes_x-fem_2002}, based on the idea of introducing a fictitious domain larger than the domain under consideration. We are interested here in another non-conformal method, which we'll present in more detail later, called stem:[\phi]-FEM. We'll only use it in the context of Poisson problem solving, for Dirichlet boundary conditions \cite{duprez_phi-fem_2020}. But the method has been extended to Neumann conditions \cite{duprez_new_2023} and then to solve various mechanical problems, including linear elasticity \cite[Chapter~2]{cotin_phi-fem_nodate}, heat transfer problems \cite[Chapter~5]{cotin_phi-fem_nodate} and the Stokes problem \cite{duprez_phi-fem_2023}

