:stem: latexmath
:xrefstyle: short
= Objectives

The main objective of the internship was to combine finite element methods and Machine Learning in order to solve the Poisson problem with Dirichlet condition. More precisely, we want to train a neural network called Fourier Neural Network (FNO) \cite{li_fourier_2021} to predict the solutions of a PDE for a given problem family (i.e. a "type" of source term). This neural network is trained with a data set consisting of the stem:[\phi]-FEM solutions of the problems considered. The predictions of this neural network will then be fed back into a finite element solver to apply a correction to improve the accuracy of the solution : this was the subject covered during the internship. The finite element methods considered will be presented in xref:FEM.adoc[Section "Finite Element Methods (FEMs)"] and the FNO in xref:fourier.adoc[Section "Fourier Neural Operator (FNO)"].

It is important to note that the stem:[\phi]-FEM method has an advantage that is very interesting in the context of organ geometries. Indeed, this type of geometry can deform in time and meshing a fictitious domain around this geometry avoids having to remesh the geometry in time. Thus only the level-set function will be modified and the mesh can be fixed. Moreover, a Cartesian mesh of the fictitious domain allows us to use the same type of neural network as those applied to images (especially FNO).

To be more precise, we will test different correction methods (presented in xref:corr/subsec_1.adoc[Section "Presentation of the different correction methods considered"]) on different problems (presented in xref:corr/subsec_0.adoc[Section "Presentation of different problems considered"]) which will enable us to use the network prediction to help the solver get as close as possible to the solution. We will start by testing these different types of solver on an analytical solution (<<_correction_on_exact_solution>>), then on a "manually perturbed" solution (<<_correction_on_disturbed_solution>>) and finally on a stem:[\phi]-FEM solution (<<_correction_on_stem:[\phi]-fem_solution>>).

After testing the various types of correction on the previous test cases, we'll apply these same methods to the prediction of an FNO (<<_correction_with_fno>>). The main objective is to enable the combination of FNO and correction to be more accurate than the conventional stem:[\phi]-FEM solver. By first testing the different corrections on the previous test cases, we hope to get an idea of the order of errors to be expected. During the course of the internship, we realized that the results obtained on the FNO did not correspond to the expected analytical results. For this reason, other types of neural networks were considered, namely multi-perceptron networks (<<_mlp>>) and PINNs (<<_pinns>>), with the aim of checking whether the results obtained are related to the use of the FNO.

