:stem: latexmath
:xrefstyle: short
= Standard FEM

== Some notions of functional analysis.

#AJOUTER : Déf Espace de Hilbert (+ ce qu'il faut pour def ça : Espace de Soboloev ? ... ) + Déf stem:[L^2],#

== General principle of the method

Let's consider a domain stem:[\Omega] whose boundary is denoted stem:[\partial\Omega]. We seek to determine a function stem:[u] defined on stem:[\Omega], solution of a partial differential equation (PDE) for given boundary conditions.

The general approach of the finite element method is to write down the variational formulation of this PDE, thus giving us a problem of the following type:

*Variational Problem :*
[stem]
++++
\text{Find } u\in V \text{ such that } a(u,v)=l(v), \;\forall v\in V
++++

where stem:[V] is a Hilbert space, stem:[a] is a bilinear form and stem:[l] is a linear form.

To do this, we multiply the PDE by a test function stem:[v\in V], then integrate over stem:[L^2(\Omega)].

The idea of FEM is to use Galerkin's method. We then look for an approximate solution stem:[u_h] in stem:[V_h], a finite-dimensional space dependent on a positive parameter stem:[h] such that

[stem]
++++
V_h\subset V, \quad \dim V_h = N_h<\infty, \quad \forall h>0
++++

The variational problem can then be approached by :

*Approach Problem :*
[stem]
++++
\text{Find } u_h\in V_h \text{ such that } a(u_h,v_h)=l(v_h), \;\forall v_h\in V
++++

As stem:[V_h] is of finite dimension, we can consider a basis stem:[(\varphi_1,\dots,\varphi_{N_h})] of stem:[V_h] and thus decompose stem:[u_h] on this basis as :

[stem]
++++
\label{decomp1}
u_h=\sum_{i=1}^{N_h}u_i\varphi_i	
++++

The approached problem is then rewritten as

[stem]
++++
\text{Find } u_1,\dots,u_{N_h} \text{ such that } \sum_{i=1}^{N_h}u_i a(\varphi_i,v_h)=l(v_h), \;\forall v_h\in V 
++++

and

[stem]
++++
\text{Find } u_1,\dots,u_{N_h} \text{ such that } \sum_{i=1}^{N_h}u_i a(\varphi_i,\varphi_j)=l(\varphi_j), \;\forall j\in \{1,\dots,N_h\}
++++

Solving the PDE involves solving the following linear system:
[stem]
++++
AU=b
++++
with
[stem]
++++
A=(a(\varphi_i,\varphi_j))_{1\le i,j\le N_h}, \quad U=(u_i)_{1\le i\le N_h} \quad \text{and} \quad b=(l(\varphi_j))_{1\le j\le N_h}
++++

== Some details on FEM

#Notions à aborder : ef de Lagrange + unisolvance + maillage + Transformation géométrique#

After having seen the general principle of FEM, it remains to define the stem:[V_h] spaces and the stem:[\{\varphi_i\}] basis functions.


[NOTE]
====
The choice of stem:[V_h] space is fundamental to have an efficient method that gives a good approximation stem:[u_h] of stem:[u]. In particular, the choice of the stem:[\{\varphi_i\}] basis of stem:[V_h] influences the structure of the stem:[A] matrix in terms of its sparsity and its condition number.
====

=== Finite Lagrange Element

\trad{Le type le plus classique et le plus simple d'éléments finis sont les éléments finis de Lagrange.}


[]
====
*Defintion (Lagrange Finite Element).*
\trad{Un élément fini de Lagrange est un triplet stem:[(K,\Sigma,P)] tel que 

*  stem:[K] est un élément géométrique de stem:[\mathbb{R}^n] (stem:[n=1,2] ou stem:[3]), compact, connexe et d'intérieur non vide.
*  stem:[\Sigma=\{a_1,\dots,a_N\}] est un ensemble fini de stem:[N] points distincts de stem:[K].
*  stem:[P] est un espace vectoriel de dimension finie de fonctions réelles définies sur stem:[K] et tel que stem:[\Sigma] soit stem:[P]-unisolvant (donc stem:[\dim P=N]).

====


[NOTE]
====
\trad{On dit que stem:[\Sigma] est stem:[P]-unisolvant si et seulement si pour tous réels stem:[\alpha_1,\dots,\alpha_N], il existe un unique élément stem:[p] de stem:[P] tel que stem:[p(a_i)=\alpha_i,i=1,\dots,N]. 
Ceci revient à dire que la fonction}
[stem]
++++
\begin{aligned}
L \; : \; P &\rightarrow \mathbb{R}^N \\
p &\mapsto(p(a_1),\dots,p(a_N))
\end{aligned}
++++
\trad{est bijective.}
====


[NOTE]
====
En pratique, pour montrer que stem:[\Sigma] est stem:[P]-unisolvant, on vérifiera simplement que stem:[\dim P=card(\Sigma)] puis on montrera l'injectivité ou la surjectivité de stem:[L]. L'injectivité  de stem:[L] se démontre en établissant que la seule fonction de stem:[P] s'annulant sur tous les points de stem:[\Sigma] est la fonction nulle. La surjectivité de stem:[L] se démontre en exhibant une famille stem:[p_1,\dots,p_N] d'éléments de stem:[P] tels que stem:[p_i(a_j)=\delta_{ij}]. En effet, étant donné des réels stem:[\alpha_1,\dots,\alpha_N], la fonction stem:[p=\sum_{i=1}^N\alpha_i p_i] vérifie alors stem:[p(a_j)=\alpha_j,j=1\dots,N]. 
====

#A mettre plus loin (base de stem:[P_1] à définir d'abord)#

---
*Example.*
\trad{Soit stem:[K] le segment stem:[[a_1,a_2]]. Montrons que stem:[\Sigma=\{a_1,a_2\}] est stem:[P]-unisolvant pour stem:[P=\mathbb{P}^1]. Comme stem:[\{1,x\}] est une base de stem:[\mathbb{P}^1], on a bien stem:[\dim P = \text{card } \Sigma = 2]. 

De plus, on peut écrire stem:[p_i=\alpha_i x+\beta_i, i=1,2]. Ainsi
[stem]
++++
\left\{\begin{aligned}
&p_1(a_1)=1 \\
&p_1(a_2)=0
\end{aligned}\right. \quad \iff	\quad
\left\{\begin{aligned}
&\alpha_1 a_1+\beta_1=1 \\
&\alpha_1 a_2+\beta_1=0
\end{aligned}\right. \quad \iff \quad
\left\{\begin{aligned}
&\alpha_1 = \frac{1}{a_1-a_2} \\
&\beta_1 = -\frac{a_2}{a_1-a_2}
\end{aligned}\right.
++++
et
[stem]
++++
\left\{\begin{aligned}
&p_2(a_1)=0 \\
&p_2(a_2)=1
\end{aligned}\right. \quad \iff	\quad
\left\{\begin{aligned}
&\alpha_2 a_1+\beta_2=0 \\
&\alpha_2 a_2+\beta_2=1
\end{aligned}\right. \quad \iff \quad
\left\{\begin{aligned}
&\alpha_1 = \frac{1}{a_2-a_1} \\
&\beta_1 = -\frac{a_1}{a_2-a_1}
\end{aligned}\right.
++++
Donc
[stem]
++++
p_1(x)=\frac{x-a_2}{a_1-a_2} \quad \text{and} \quad p_2(x)=\frac{x-a_1}{a_2-a_1}
++++
On en déduit la surjectivité de stem:[L] et stem:[\Sigma] est stem:[\mathbb{P}^1]-unisolvant.}

---

=== Mesh

\trad{La première étape consiste à construire un maillage de stem:[\Omega].}


[NOTE]
====
\trad{La partie de génération de maillage est une étape importante }
====

== Application to the Poisson problem

#Ajouter formulation variationnel Poisson#


[]
====
*Propositon (Lax-Milgram).*

Let stem:[a] be a continuous, coercive bilinear form on stem:[V] and stem:[l] a continuous, linear form on stem:[V]. Then the variational problem has a unique solution stem:[u\in V]. 

Moreover, if the bilinear form is symmetrical, stem:[u] is a solution to the following minimization problem:
[stem]
++++
J(u)=\min_{v\in V} J(v), \quad J(v)=\frac{1}{2}a(v,v)-l(v)
++++
====

It can then be shown that the Poisson problem with Dirichlet condition has a unique weak solution.

#rajouter preuve#

