:stem: latexmath
:xrefstyle: short
= Standard FEM

== Some notions of functional analysis.

#AJOUTER : Déf Espace de Hilbert (+ ce qu'il faut pour def ça : Espace de Soboloev ? ... ) + Déf stem:[L^2],#

== General principle of the method

Let's consider a domain stem:[\Omega] whose boundary is denoted stem:[\partial\Omega]. We seek to determine a function stem:[u] defined on stem:[\Omega], solution of a partial differential equation (PDE) for given boundary conditions.

The general approach of the finite element method is to write down the variational formulation of this PDE, thus giving us a problem of the following type:

*Variational Problem :*
[stem]
++++
\text{Find } u\in V \text{ such that } a(u,v)=l(v), \;\forall v\in V
++++

where stem:[V] is a Hilbert space, stem:[a] is a bilinear form and stem:[l] is a linear form.

To do this, we multiply the PDE by a test function stem:[v\in V], then integrate over stem:[L^2(\Omega)].

The idea of FEM is to use Galerkin's method. We then look for an approximate solution stem:[u_h] in stem:[V_h], a finite-dimensional space dependent on a positive parameter stem:[h] such that

[stem]
++++
V_h\subset V, \quad \dim V_h = N_h<\infty, \quad \forall h>0
++++

The variational problem can then be approached by :

*Approach Problem :*
[stem]
++++
\text{Find } u_h\in V_h \text{ such that } a(u_h,v_h)=l(v_h), \;\forall v_h\in V
++++

As stem:[V_h] is of finite dimension, we can consider a basis stem:[(\varphi_1,\dots,\varphi_{N_h})] of stem:[V_h] and thus decompose stem:[u_h] on this basis as :

[stem]
++++
\label{decomp1}
u_h=\sum_{i=1}^{N_h}u_i\varphi_i	
++++

The approached problem is then rewritten as

[stem]
++++
\text{Find } u_1,\dots,u_{N_h} \text{ such that } \sum_{i=1}^{N_h}u_i a(\varphi_i,v_h)=l(v_h), \;\forall v_h\in V 
++++

and

[stem]
++++
\text{Find } u_1,\dots,u_{N_h} \text{ such that } \sum_{i=1}^{N_h}u_i a(\varphi_i,\varphi_j)=l(\varphi_j), \;\forall j\in \{1,\dots,N_h\}
++++

Solving the PDE involves solving the following linear system:
[stem]
++++
AU=b
++++
with
[stem]
++++
A=(a(\varphi_i,\varphi_j))_{1\le i,j\le N_h}, \quad U=(u_i)_{1\le i\le N_h} \quad \text{and} \quad b=(l(\varphi_j))_{1\le j\le N_h}
++++

== Some details on FEM

#Notions à aborder : ef de Lagrange + unisolvance + maillage + Transformation géométrique#

After having seen the general principle of FEM, it remains to define the stem:[V_h] spaces and the stem:[\{\varphi_i\}] basis functions.


[NOTE]
====
The choice of stem:[V_h] space is fundamental to having an efficient method that gives a good approximation stem:[u_h] of stem:[u]. In particular, the choice of the stem:[\{\varphi_i\}] basis of stem:[V_h] influences the structure of the stem:[A] matrix in terms of its sparsity and condition number.
====

#TO COMPLETE !#

=== Finite Lagrange Element
=== Mesh

[NOTE]
====
====

== Application to the Poisson problem

#Ajouter formulation variationnel Poisson#


[NOTE]
====
*Propositon (Lax-Milgram).*

Let stem:[a] be a continuous, coercive bilinear form on stem:[V] and stem:[l] a continuous, linear form on stem:[V]. Then the variational problem has a unique solution stem:[u\in V]. 

Moreover, if the bilinear form is symmetrical, stem:[u] is a solution to the following minimization problem:
[stem]
++++
J(u)=\min_{v\in V} J(v), \quad J(v)=\frac{1}{2}a(v,v)-l(v)
++++
====

It can then be shown that the Poisson problem with Dirichlet condition has a unique weak solution.

#rajouter preuve#

