:stem: latexmath
:xrefstyle: short
= Conclusion

The main objective of the internship was to combine finite element methods and machine learning in order to solve the Poisson problem with boundary Dirichlet condition. More precisely, we wanted to train an FNO to predict the solutions of a PDE for a given family of problems and apply a correction to them using finite element solvers with the aim of improving the accuracy of the solution. 

We have considered 2 types of solution correction methods, the first is an addition correction method and the second is a multiplication correction method, which have been treated by the FEM and stem:[\phi]-FEM methods. We have chosen here the case of fairly simple solutions on very simple and fixed geometries, which have enabled us to obtain numerical results on analytical solutions. These test cases have enabled us to confirm that the correction methods considered are functional, and have also confirmed some of the theoretical results obtained. These initial test cases also enabled us to identify some of the limitations of these correction methods, particularly in terms of the degrees of the chosen spaces.  

 We were then able to apply these various correction methods to the predictions made by the FNO, and it turned out that the results were not satisfactory. As a result, we began to look for methods to increase the degree of the solution in order to bring us back to the results obtained in the analytical cases. The first idea was to decompose the FNO output into a series of polynomials ( notably Legendre polynomials) in order to evaluate the solution at any point in our domain and thus consider the high-degree solution.

As the results were inconclusive, we turned to neural networks. Putting the FNO to one side, we set out to build a neural network model capable of predicting a solution at any point in the domain. We began by considering an MLP network, whose lack of learning on derivatives proved problematic. We then moved on to PINNs, which, by learning the solution, also learn its derivatives, enabling us to reduce the error made by conventional methods (FEM and stem:[\phi]-FEM) by a factor of around 100 (in the case of correction by addition). 

Following on from what has already been done, we could then try adding PINNs to the output of the FNO, in other words, adding a layer output that would replace the decomposition into a series of polynomials and enable us to have the solution at any point in the domain. We could also carry out some documentation work to find more suitable models than the FNO. Finally, we could consider more complex and time-varying geometries (such as 3D organ geometries).