:stem: latexmath
:xrefstyle: short
= First domain : the Circle.

Here, we'll consider the stem:[\Omega] domain to be the circle of radius stem:[\sqrt{2}/4] and center stem:[(0.5,0.5)].This domain is entirely included in the fictitious domain stem:[O=[0,1]^2] (<<geom_circle>>).

We will consider the levelset function stem:[\phi] defined by
[stem]
++++
\phi(x,y)=-1/8+(x-1/2)^2+(y-1/2)^2,
++++
negative function inside the domain, null at the boundary and positive outside it

We then consider different problems #à compléter#.

== First problem

Here, we are interested in the Poisson problem with an analytical solution
[stem]
++++
u_{ex}(x,y)=S\times\sin\left(8\pi f\left((x-0.5)^2+(y-0.5)^2\right)+\varphi\right)
++++
where stem:[S\in[0,1]] is the amplitude of the signal, stem:[f\in\mathbb{N}] can be associated with the "frequency" of the signal and stem:[\varphi\in[0,1]] the phase at the origin

Thus, the second associated member is defined by
[stem]
++++
\begin{aligned}
f(x,y)=256\pi^2 S f^2&\left((x-0.5)^2+(y-0.5)^2\right)\sin\left[8\pi f\left((x-0.5)^2+(y-0.5)^2\right) + \varphi\right] \\
&- 32\pi S f\cos\left[8\pi f \left((x-0.5)^2+(y-0.5)^2\right) + \varphi\right]
\end{aligned}
++++


[NOTE]
====
Note that for stem:[\varphi=0], the Dirichlet conditions considered are then homogeneous on the circle (i.e. stem:[g=0] on stem:[\Gamma]).
====

#ajouter image solution et f#

#ajouter les autres cas tests : f gaussienne...#

== stem:[f] Gaussian
[stem]
++++
++++

