:stem: latexmath
:xrefstyle: short
= Correction by multiplying on an elevated problem

We now introduce a third correction method, which we will call correction by multiplying on an elevated problem. This method is in fact very similar to the previous one (correction by multiplying), except that we are no longer trying to correct the same problem.

The initial modified problem, which we now consider, consists in finding stem:[u : \Omega \rightarrow \mathbb{R}^d] such that
[stem]
++++
\left\{
\begin{aligned}
-\Delta \hat{u} = f, \; &&\text{in } \; \Omega, \\
\hat{u}=g+m, \; &&\text{on } \; \Gamma,
\end{aligned}
\right. %\tag{stem:[\mathcal{P}^\mathcal{M}]}
++++
with stem:[\hat{u}=u+m] and stem:[m] a constant.

We then apply the same multiplication correction method, but this time on the modified problem, which has been elevated by a constant stem:[m]. We then consider
[stem]
++++
\tilde{u}=\hat{\phi}C
++++
with 
[stem]
++++
\hat{\phi}=\tilde{\phi}+m
++++
and so we look for stem:[C: \Omega \rightarrow \mathbb{R}^d] solution to the problem
[stem]
++++
\label{eq.corr.pbc_mult_reh}
\left\{\begin{aligned}
&-\Delta (\hat{\phi}C)=f, \; &&\text{in } \; \Omega, \\
&C=1, \; &&\text{on } \; \Gamma.
\end{aligned}\right. %\tag{stem:[\mathcal{C}_\times^\mathcal{M}]}
++++

So for the standard FEM method, the weak formulation will be given by
[stem]
++++
\int_\Omega \nabla (\hat{\phi}C)\cdot\nabla (\hat{\phi}v)=\int_\Omega f\hat{\phi}v
++++
where homogeneous or non-homogeneous Dirichlet conditions can be strongly imposed by classical methods (penalization, elimination...)

For the stem:[\phi]-FEM method, the weak formulation for the homogeneous problem is given by
[stem]
++++
\int_{\Omega_h} \nabla (\hat{\phi} C) \cdot \nabla (\hat{\phi} v) - \int_{\partial\Omega_h} \frac{\partial}{\partial n}(\hat{\phi} C)\hat{\phi} v+G_h(w,v)=\int_{\Omega_h} f \hat{\phi} v + G_h^{rhs}(v)
++++
with
[stem]
++++
G_h(C,v)=\sigma h\sum_{E\in\mathcal{F}_h^\Gamma} \int_E \left[\frac{\partial}{\partial n}(\hat{\phi} C)\right] \left[\frac{\partial}{\partial n}(\hat{\phi} v)\right]+\sigma h^2\sum_{T\in\mathcal{T}_h^\Gamma} \int_{T} \Delta(\hat{\phi} C)\Delta(\hat{\phi} v)
++++
and
[stem]
++++
G_h^{rhs}(v)=-\sigma h^2\sum_{T\in\mathcal{T}_h^\Gamma} \int_{T} f \Delta(\hat{\phi} v).
++++

In the case of this correction, whether the problem is homogeneous or non-homogeneous, the correction problem is non-homogeneous (for stem:[m\ne 0]), so it is important to impose the boundary conditions either by the direct method in xref:FEM/subsec_1_subsubsec_2.adoc[Section "Description of the stem:[\phi]-FEM direct method"] or by the dual method presented in xref:FEM/subsec_1_subsubsec_3.adoc[Section "Description of the stem:[\phi]-FEM dual method"].


[NOTE]
====
Note that if the problem is sufficiently elevated for its solution to be strictly positive, the operation of bringing stem:[C=\frac{\tilde{u}}{\hat{\phi}}] closer to 1 doesn't pose any problem (since in this case stem:[\hat{\phi}\ne 0]). Moreover, we can easily return to the original problem by subtracting stem:[m] from stem:[\tilde{u}].
====

