:stem: latexmath
:xrefstyle: short
= Correction by multiplying on an elevated problem
= Correction by multiplying on an elevated problem

We now introduce a third correction method, which we'll call multiplication correction on an elevated problem. This method is in fact very similar to the previous one (correction by multiplication), except that we are no longer trying to correct the same problem.

The initial modified problem, which we now consider, consists in finding stem:[u : \Omega \rightarrow \mathbb{R}^d] such that
[stem]
++++
\label{eq.corr.pb_reh}
\left\{
\begin{aligned}
-\Delta \hat{u} = f, \; &&\text{in } \; \Omega, \\
\hat{u}=g+m, \; &&\text{on } \; \Gamma,
\end{aligned}
\right. \tag{stem:[\mathcal{P}^\mathcal{M}]}
++++
with stem:[\hat{u}=u+m] and stem:[m] a constant.

#ajouter schéma (à gauche une solution initiale simple et à droite la solution rehaussée.)#

We then apply the same multiplication correction method, but this time on the modified problem, which has been elevated by a constant stem:[m]. We then consider
[stem]
++++
\tilde{u}=\hat{\phi}C
++++
avec 
[stem]
++++
\hat{\phi}=\tilde{\phi}+m
++++
and so we look for stem:[C: \Omega \rightarrow \mathbb{R}^d] solution to the problem
[stem]
++++
\label{eq.corr.pbc_mult_reh}
\left\{\begin{aligned}
&-\Delta (\hat{\phi}C)=f \quad &&\Omega \\
&C=1 \quad &&\Gamma
\end{aligned}\right. \tag{stem:[\mathcal{C}_\times^\mathcal{M}]}
++++


[NOTE]
====
Note that if the problem is sufficiently elevated for its solution to be strictly positive, the operation of bringing stem:[C=\frac{\tilde{u}}{\hat{\phi}}] closer to 1 doesn't pose a problem (since in this case stem:[\hat{\phi}\ne 0]). Moreover, we can easily return to the original problem by subtracting stem:[m] from stem:[\tilde{u}]. In this way, by correcting the elevated problem by multiplication, we can easily return to correcting the initial problem by multiplication. #En annexe, on a un document expliquant l'intérêt de rehausser le problème +add ref.#
====

