:stem: latexmath
:xrefstyle: short
= Theorical results

The aim of this section is to present some interesting theoretical results. We begin by presenting the interest of elevating the problem in xref:corr/subsec_2_subsubsec_0.adoc[Section "Interest of elevating the problem"]. We will then present an interesting result for standard FEM in xref:corr/subsec_2_subsubsec_1.adoc[Section "Comparaison of correction methods"]. In fact, we'll show that the solution obtained by the multiplication correction on the elevated problem converges to the solution obtained by the addition correction when stem:[m] tends to infinity. Finally, we will demonstrate the estimation error of the correction on the elevated problem in xref:corr/subsec_2_subsubsec_2.adoc[Section "Error estimation of the correction on the elevated problem"].


---
The features include

** xref:corr/subsec_2_subsubsec_0.adoc[Interest of elevating the problem]

** xref:corr/subsec_2_subsubsec_1.adoc[Comparaison of correction methods]

** xref:corr/subsec_2_subsubsec_2.adoc[Error estimation of the correction on the elevated problem]

