:stem: latexmath
:xrefstyle: short
= Interest of elevating the problem

The aim of this section is to explain the interest in elevating the problem in the case of the multiplication correction presented in xref:corr/subsec_1_subsubsec_2.adoc[Section "Correction by multiplying on an elevated problem"] with a stem:[\mathbb{P}^1] solution. Only the standard FEM method is considered here. For this purpose, we'll consider a so-called disturbed solution, i.e. one that is close to the exact solution. We assume we have an analytical solution to the problem, denoted stem:[u_{ex}], to which we'll apply a perturbation, denoted stem:[P]. We then define
[stem]
++++
\tilde{\phi}(x,y) = u(x,y)+\epsilon P(x,y)
++++
with stem:[P] the perturbation (such that stem:[P=0] on stem:[\Gamma]) and stem:[\epsilon] small.

[stem]
++++
++++
[stem]
++++
++++
[stem]
++++
++++
[stem]
++++
++++

We pose
[stem]
++++
\hat{\phi}=\tilde{\phi}+m
++++
with stem:[m] a constant, and consider the multiplication correction on a elevated problem, defined in xref:corr/subsec_1_subsubsec_2.adoc[Section "Correction by multiplying on an elevated problem"] by the problem
[stem]
++++
\left\{\begin{aligned}
&-\Delta (\hat{\phi}C)=f \quad &&\Omega \\
&\hat{u}=g+m \quad &&\Gamma
\end{aligned}\right.
++++
with stem:[\hat{u}=\hat{\phi}C].

In Section #add section#, we'll show the following inequality in the context of this problem

[stem]
++++
\left|\left|\hat{u_{ex}}-\hat{u_h}\right|\right|_0\le ch^{k+1}||\hat{\phi}||_\infty\left|C\right|_{k+1,\Omega}
++++

with stem:[c] a constant, stem:[\hat{u_{ex}}=u_{ex}+m] and stem:[C=\frac{u_{ex}+m}{\hat{\phi}}].

For stem:[k=1], we then have
[stem]
++++
|C|_{2,\Omega}=\left|\frac{u_{ex}+m}{\hat{\phi}}\right|_{2,\Omega}=\left|\left|\left(\frac{u_{ex}+m}{\hat{\phi}}\right)''\right|\right|_{0,\Omega}=\epsilon\left|\left|\left(\frac{P}{\hat{\phi}}\right)''\right|\right|_{0,\Omega}=\epsilon\left|\left|\left(\frac{P}{\tilde{\phi}+m}\right)''\right|\right|_{0,\Omega}
++++
with
[stem]
++++
\begin{aligned}
\left(\frac{P}{\tilde{\phi}+m}\right)''&=\frac{P''(\tilde{\phi}+m)-P\tilde{\phi}''}{(\tilde{\phi}+m)^2}+\frac{2(P\tilde{\phi}'-P'(\tilde{\phi}+m))\tilde{\phi}'}{(\tilde{\phi}+m)^3} \\
&=\frac{P''\tilde{\phi}-P\tilde{\phi}''}{(\tilde{\phi}+m)^2}+\frac{2(P\tilde{\phi}'-P'\tilde{\phi})\tilde{\phi}'}{(\tilde{\phi}+m)^3}+    \frac{mP''}{(\tilde{\phi}+m)^2}-\frac{2mP'\tilde{\phi}'}{(\tilde{\phi}+m)^3}
\end{aligned}
++++

As 
[stem]
++++
\left|\left|\left(\frac{P}{\tilde{\phi}+m}\right)''\right|\right|_{L^2(\Omega)}=\left|\left|\left(\frac{P}{m\left(1+\frac{\tilde{\phi}}{m}\right)}\right)''\right|\right|_{L^2(\Omega)}=\frac{1}{m}\left|\left|\left(\frac{P}{1+\frac{\tilde{\phi}}{m}}\right)''\right|\right|_{L^2(\Omega)}
++++
and 
[stem]
++++
\begin{aligned}
\left(\frac{P}{1+\frac{\tilde{\phi}}{m}}\right)''=m\left(\frac{P}{\hat{\phi}}\right)''&=\frac{m(P''\tilde{\phi}-P\tilde{\phi}'')}{(\tilde{\phi}+m)^2}+\frac{2m(P\tilde{\phi}'-P'\tilde{\phi})\tilde{\phi}'}{(\tilde{\phi}+m)^3}+    \frac{m^2P''}{(\tilde{\phi}+m)^2}-\frac{2m^2P'\tilde{\phi}'}{(\tilde{\phi}+m)^3} \\
&=\frac{m(P''\tilde{\phi}-P\tilde{\phi}'')}{m^2\left(1+\frac{\tilde{\phi}}{m}\right)^2}+\frac{2m(P\tilde{\phi}'-P'\tilde{\phi})\tilde{\phi}'}{m^3\left(1+\frac{\tilde{\phi}}{m}\right)^3}+    \frac{m^2P''}{m^2\left(1+\frac{\tilde{\phi}}{m}\right)^2}-\frac{2m^2P'\tilde{\phi}'}{m^3\left(1+\frac{\tilde{\phi}}{m}\right)^3} \\
&=\frac{P''\tilde{\phi}-P\tilde{\phi}''}{m\left(1+\frac{\tilde{\phi}}{m}\right)^2}+\frac{2(P\tilde{\phi}'-P'\tilde{\phi})\tilde{\phi}'}{m^2\left(1+\frac{\tilde{\phi}}{m}\right)^3}+    \frac{P''}{\left(1+\frac{\tilde{\phi}}{m}\right)^2}-\frac{2P'\tilde{\phi}'}{m\left(1+\frac{\tilde{\phi}}{m}\right)^3} \\
\end{aligned}
++++
then, for stem:[m] sufficiently large :
[stem]
++++
\left|\left|\left(\frac{P}{1+\frac{\tilde{\phi}}{m}}\right)''\right|\right|_{L^2(\Omega)}\sim\left|\left|P''\right|\right|_{L^2(\Omega)}
++++

So for stem:[m] sufficiently large, we have stem:[||\hat{\phi}||_\infty\sim m] and thus
[stem]
++++
\left|\left|\frac{u+m}{\hat{\phi}}-C_h\right|\right|_{L^2(\Omega)}\le ch^{k+1}\epsilon\left|\left|P''\right|\right|_{L^2(\Omega)} \label{ine3_bis}
++++

We deduce that when stem:[m] is big, the error no longer depends on the solution but only on the perturbation stem:[P]. These results were obtained numerically and are presented in xref:corr/subsec_3_subsubsec_1.adoc[Section "Correction on disturbed solution"].

However, when stem:[m] is small, we can see that the error is dominated by the first derivatives and second derivatives of the disturbed solution stem:[tilde{\phi}].


[NOTE]
====
In addition, raising the problem can be extremely effective when the solution cancels out on the domain. 
====


[NOTE]
====
Note that in the case of the addition correction presented in xref:corr/subsec_1_subsubsec_0.adoc[Section "Correction by adding"], raising the problem is of no interest.
====

