:stem: latexmath
:xrefstyle: short
= Correction by multiplying

In this second method, we try to approach the exact solution in a different way. In fact, we want to bring the factor between the stem:[\tilde{\phi}] solution and the solution of the corrected problem closer to 1. In other words, by considering 
[stem]
++++
\tilde{u}=\tilde{\phi}C,
++++
we try to bring stem:[C=\frac{\tilde{u}}{\tilde{\phi}}] closer to 1 (for stem:[\tilde{\phi}\ne 0]). This type of correction is called correction by multiplying.

So we're looking for stem:[C: \Omega \rightarrow \mathbb{R}^d] solution to the problem
[stem]
++++
\left\{\begin{aligned}
&-\Delta (\tilde{\phi}C)=f, \; &&\text{on } \Omega, \\
&C=1, \; &&\text{on } \; \Gamma.
\end{aligned}\right. %\tag{stem:[\mathcal{C}_\times]}
++++


[NOTE]
====
In the same way as for correction by adding, we note that this problem is equivalent to the initial problem.
====

So for the standard FEM method, the weak formulation will be given by
[stem]
++++
\int_\Omega \nabla (\tilde{\phi}C)\cdot\nabla (\tilde{\phi}v)=\int_\Omega f\tilde{\phi}v
++++
where homogeneous or non-homogeneous Dirichlet conditions can be strongly imposed by classical methods (penalization, elimination...).

For the stem:[\phi]-FEM method, the weak formulation for the homogeneous problem is given by
[stem]
++++
\int_{\Omega_h} \nabla (\tilde{\phi} C) \cdot \nabla (\tilde{\phi} v) - \int_{\partial\Omega_h} \frac{\partial}{\partial n}(\tilde{\phi} C)\tilde{\phi} v+G_h(w,v)=\int_{\Omega_h} f \tilde{\phi} v + G_h^{rhs}(v)
++++
with
[stem]
++++
G_h(C,v)=\sigma h\sum_{E\in\mathcal{F}_h^\Gamma} \int_E \left[\frac{\partial}{\partial n}(\tilde{\phi} C)\right] \left[\frac{\partial}{\partial n}(\tilde{\phi} v)\right]+\sigma h^2\sum_{T\in\mathcal{T}_h^\Gamma} \int_{T} \Delta(\tilde{\phi} C)\Delta(\tilde{\phi} v)
++++
and
[stem]
++++
G_h^{rhs}(v)=-\sigma h^2\sum_{T\in\mathcal{T}_h^\Gamma} \int_{T} f \Delta(\tilde{\phi} v).
++++

In the non-homogeneous case, it is important to impose the boundary conditions either by the direct method in xref:FEM/subsec_1_subsubsec_2.adoc[Section "Description of the stem:[\phi]-FEM direct method"] or by the dual method presented in xref:FEM/subsec_1_subsubsec_3.adoc[Section "Description of the stem:[\phi]-FEM dual method"].

