name: CI

on: [push]

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'flecourtier/phifem_stage' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go
    

  build_docs:
    needs: activate
    runs-on: ubuntu-latest
    name: Build, Install, Package documentation
    if: "!contains(github.event.head_commit.message, 'docs skip')"
    steps:
    - uses: actions/checkout@v3
    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.DOCS_GITHUB_KEY }}
    - name: Run convert
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 convert_latex_to_antora.py
    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        npm install
        npm run antora
      working-directory: docs/antora
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/antora/public # The folder the action should deploy.